language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    # Latest dependencies with all PHP versions
    - php: 7.3
      env:
        PHP_INI='xdebug.mode=coverage'
    - php: 7.4
      env:
        PHP_INI='xdebug.mode=coverage'
    - php: 8.0
      # Ignore the platform requirements for the upcoming PHP version
    - php: nightly
      env: COMPOSER_FLAGS='--ignore-platform-reqs'
  allow_failures:
    - php: nightly
  fast_finish: true

branches:
  only:
    - master
    - develop

install:
  - curl -s http://getcomposer.org/installer | php
  - php composer.phar install --no-interaction $COMPOSER_FLAGS
  - if [[ -n $PHP_INI ]]; then echo $PHP_INI >> ~/.phpenv/versions/$(phpenv version-name)/etc/php.ini; fi

script:
  - mkdir -p build/logs;
  - composer phpunit

after_success:
  - travis_retry php vendor/bin/php-coveralls -v

notifications:
  email:
    - danny.vandersluijs@icloud.com